### ISSUE TITLE
能否加上下载评论的功能？

### ISSUE THREAD

**Issue by cl165** [cv-cat/Spider_XHS#14]
如题

**Comment by cv-cat** [comment]
下载评论是要收费的

**Comment by US579** [comment]
@cl165 随便写的 仅供参考
https://github.com/cv-cat/Spider_XHS/compare/master...US579:Spider_XHS:master

**Comment by cl165** [comment]
> @cl165 随便写的 仅供参考 [master...US579:Spider_XHS:master](https://github.com/cv-cat/Spider_XHS/compare/master...US579:Spider_XHS:master)
> 
> <img alt="Screenshot 2024-01-08 at 14 45 02" width="1477" src="https://private-user-images.githubusercontent.com/37062041/294808604-b0e0787f-49f1-4442-93b4-ec9a349bf9bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODY2MDUsIm5iZiI6MTcwNDY4NjMwNSwicGF0aCI6Ii8zNzA2MjA0MS8yOTQ4MDg2MDQtYjBlMDc4N2YtNDlmMS00NDQyLTkzYjQtZWM5YTM0OWJmOWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAzNTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0MzhmNjI0MDYxM2YxNDRhM2ZiNWMxOWFlY2JmZThjZmIyYjgyMzZiMmQ5OWRiYzk1NzE3YTFhNGY4NWEyZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qlffdxlpjIPBaO1qqx_AcjI0MreJd2WK3_7cfJkHtQw"> <img alt="Screenshot 2024-01-08 at 14 45 41" width="1443" src="https://private-user-images.githubusercontent.com/37062041/294808674-ecb10b3e-58d6-4af1-911a-93c73fdd86ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2ODY2MDUsIm5iZiI6MTcwNDY4NjMwNSwicGF0aCI6Ii8zNzA2MjA0MS8yOTQ4MDg2NzQtZWNiMTBiM2UtNThkNi00YWYxLTkxMWEtOTNjNzNmZGQ4NmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDAzNTgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZjY1ZjI5Nzc2ZTE5NDNhZjZlMjI4ODNmZDM5MGVkZWU0ZTdmMTVhNGQ2NTljYWM2ZGM5ZmRiY2IwMWE4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H5HOOHdCXb4cLczcZ2BiNvymbA2-PqzpMGC1dm2VYEE">

谢谢兄弟哈
