### ISSUE TITLE
下载运行cookie有效却搜索不到东西打印发现返回为成功却不携带任何信息

### ISSUE THREAD

**Issue by yangCHEN121520** [cv-cat/Spider_XHS#19]

**Comment by yangCHEN121520** [comment]
似乎是没有通过验证吗，但是cookie有效

**Comment by foobarhe** [comment]
应该返回类似`{'code': 0, 'success': True, 'msg': '成功', 'data': {}}` 感觉这个方式失效了？还是账号被封了？

**Comment by railwaygun** [comment]
我也是返回了类似{'code': 0, 'success': True, 'msg': '成功', 'data': {}}这样的

**Comment by Seven-Circles** [comment]
我也是返回的{'code': 0, 'success': True, 'msg': '成功', 'data': {}}

**Comment by yangCHEN121520** [comment]
我修改了cookie，应该是cookie多了几个参数包括ab别的记不得了，你们可以尝试下除了cookie里面一个空列表和另外某个看起来不重要的参数，然后程序就运行正常了。

**Comment by yangCHEN121520** [comment]
@Seven-Circles @railwaygun @foobarhe

**Comment by foobarhe** [comment]
> 我修改了cookie，应该是cookie多了几个参数包括ab别的记不得了，你们可以尝试下除了cookie里面一个空列表和另外某个看起来不重要的参数，然后程序就运行正常了。

额，具体哪个参数啊？求指教。

```
{
     "sec_poison_id": "",
     "gid": "",
     "a1": "",
     "websectiga": "",
     "webId": "",
     "web_session": "",
     "xsecappid": "xhs-pc-web",
     "webBuild": "",
}
```

**Comment by yangCHEN121520** [comment]
> > 我修改了cookie，应该是cookie多了几个参数包括ab别的记不得了，你们可以尝试下除了cookie里面一个空列表和另外某个看起来不重要的参数，然后程序就运行正常了。
> 
> 额，具体哪个参数啊？求指教。
> 
> ```
> {
>      "sec_poison_id": "",
>      "gid": "",
>      "a1": "",
>      "websectiga": "",
>      "webId": "",
>      "web_session": "",
>      "xsecappid": "xhs-pc-web",
>      "webBuild": "",
> }
> ```

打开浏览器查看具体cookie参数，然后可以对比缺了什么参数，有两个看着不需要，一看就明白，或者你都试试

**Comment by foobarhe** [comment]
> > > 我修改了cookie，应该是cookie多了几个参数包括ab别的记不得了，你们可以尝试下除了cookie里面一个空列表和另外某个看起来不重要的参数，然后程序就运行正常了。
> > 
> > 
> > 额，具体哪个参数啊？求指教。
> > ```
> > {
> >      "sec_poison_id": "",
> >      "gid": "",
> >      "a1": "",
> >      "websectiga": "",
> >      "webId": "",
> >      "web_session": "",
> >      "xsecappid": "xhs-pc-web",
> >      "webBuild": "",
> > }
> > ```
> 
> 打开浏览器查看具体cookie参数，然后可以对比缺了什么参数，有两个看着不需要，一看就明白，或者你都试试

刚试了下，之前不行的cookie也可以了，感觉和我们没关系，是xhs那边调整了啥。

**Comment by yangCHEN121520** [comment]
> 是不是又不行了...

可以的 更换cookie

**Comment by yangCHEN121520** [comment]
> > > > 我修改了cookie，应该是cookie多了几个参数包括ab别的记不得了，你们可以尝试下除了cookie里面一个空列表和另外某个看起来不重要的参数，然后程序就运行正常了。
> > > 
> > > 
> > > 额，具体哪个参数啊？求指教。
> > > ```
> > > {
> > >      "sec_poison_id": "",
> > >      "gid": "",
> > >      "a1": "",
> > >      "websectiga": "",
> > >      "webId": "",
> > >      "web_session": "",
> > >      "xsecappid": "xhs-pc-web",
> > >      "webBuild": "",
> > > }
> > > ```
> > 
> > 
> > 打开浏览器查看具体cookie参数，然后可以对比缺了什么参数，有两个看着不需要，一看就明白，或者你都试试
> 
> 刚试了下，之前不行的cookie也可以了，感觉和我们没关系，是xhs那边调整了啥。

不太清楚，反正目前使用正常，实在不行就找作者花钱买下解密或者定制hhh
