### ISSUE TITLE
注意：抓取6个账号后，spider账号封禁账号现象

### ISSUE THREAD

**Issue by seanchan** [cv-cat/Spider_XHS#5]
user_list填入了6个目标账户，抓取大约3000条note后，账号被封禁
![微信图片_20231020102618](https://github.com/cv-cat/Spider_XHS/assets/2304570/e5ef0e07-2625-4612-9a79-f4bbe9e6f906)

**Comment by cv-cat** [comment]
你这可能爬的太猛了

**Comment by 2424004764** [comment]
太频繁了吧
